version: '3.5'

services:
  mysql:
    build: ./mysql/
    container_name: mysql
    tty: true
    ports: 
      - 3306:3306
    networks:
      - techies-guild
  redis:
    build: ./redis
    container_name: redis
    tty: true
    ports:
      - 6379:6379
    networks:
      - techies-guild
  api_server:
    build: ./api_server
    container_name: api_server
    tty: true
    ports:
      - 3001:3001
    depends_on:
      - mysql
      - redis
    networks:
      - techies-guild
  client:
    build: ./client
    container_name: client
    tty: true
    networks:
      - techies-guild
  nginx:
    build: ./nginx
    container_name: nginx
    tty: true
    restart: unless-stopped
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - api_server
      - client
    networks:
      - techies-guild
networks:
  techies-guild:
    driver: bridge