# COMMON
no_space: ''
uppercase: '０-９ａ-ｚＡ-Ｚ'
lowercase: '0-9a-zA-Z'
upper_space: '　'
lower_space: ' '
upper_numbers: '０-９'
lower_numbers: '0-9'

# RESPONSE
response:
  ok:
    status: 200
    result: 'OK'
  error:
    status: 500
    result: 'ERROR'

# PROJECT COMMON
price_unit_id:
  yen_per_month: 0
  yen_per_hour: 1
price_unit_name:
  yen_per_month: '円/月'
  yen_per_hour: '円/時'
operation_unit_id:
  hour: 0
skill_type:
  language: 0
  framework: 1
  db: 2
  tool: 3
  os: 4
  package: 5
  others: 6
# MIDWORKS
midworks:
  company_name: 'MIDWORKS'
  company_id: 0
  url:
    host: 'https://mid-works.com'
    new_projects: 'https://mid-works.com/projects'
  title:
    description: '業務内容'
    skill: 'スキルについて'
    required_skills: '必須スキル'
    other_skills: '歓迎スキル'
    detail: '案件詳細'
    skill_tags: '開発環境'
    price: '単価/月'
    weekly_attendance: '週出勤回数'
    location: '勤務地'
    position: '職種'
    contract: '契約形態'
    industry: '業界'
# LEVTECH
levtech:
  company_name: 'LEVTECH'
  company_id: 1
  url:
    host: 'https://freelance.levtech.jp'
    new_projects: 'https://freelance.levtech.jp/project'
  title:
    description: '職務内容'
    skill: '求めるスキル'
    skill_tags: 'この会社が扱う技術'
    price: '単価'
    location: '最寄り駅'
    position: '職種・ポジション'
    contract: '契約形態'
    contract_location: '契約形態最寄り駅'