# COMMON
no_space: ''
uppercase: '０-９ａ-ｚＡ-Ｚ'
lowercase: '0-9a-zA-Z'
upper_space: '　'
lower_space: ' '
upper_numbers: '０-９'
lower_numbers: '0-9'
pjt_list_count: 20
search:
  type:
    location: 0
    contract: 1
    industry: 2
    tag: 3
  type_list:
    all: [0, 1, 2, 3]
    location_contract_industry: [0, 1, 2]
    contract_industry_tag: [1, 2, 3]
    location_industry_tag: [0, 2, 3]
    location_contract_tag: [0, 1, 3]
    location_contract: [0, 1]
    contract_industry: [1, 2]
    industry_tag: [2, 3]
    location_tag: [0, 3]
    location: [0]
    contract: [1]
    industry: [2]
    tag: [3]
# RESPONSE
response:
  ok:
    status: 200
    result: 'OK'
  not_found:
    status: 404
    result: 'NOT FOUND'
  error:
    status: 500
    result: 'ERROR'
# PROJECT COMMON
price_unit_id:
  yen_per_month: 0
  yen_per_hour: 1
  other: 1000
price_unit_name:
  yen_per_month: '円/月'
  yen_per_hour: '円/時'
  other: 'その他'
operation_unit_id:
  hour: 0
  other: 1000
tag_type:
  language: 0
  framework: 1
  db: 2
  tool: 3
  os: 4
  package: 5
  rpa: 6
  other: 1000
# MIDWORKS
midworks:
  company_name: 'Midworks'
  company_id: 0
  url:
    host: 'https://mid-works.com'
    new_projects: 'https://mid-works.com/projects'
  title:
    description: '業務内容'
    skill: 'スキルについて'
    required_skills: '必須スキル'
    other_skills: '歓迎スキル'
    detail: '案件詳細'
    tags: '開発環境'
    price: '単価/月'
    weekly_attendance: '週出勤回数'
    location: '勤務地'
    position: '職種'
    contract: '契約形態'
    industry: '業界'
# LEVTECH
levtech:
  company_name: 'レバテック'
  company_id: 1
  url:
    host: 'https://freelance.levtech.jp'
    new_projects: 'https://freelance.levtech.jp/project'
  title:
    description: '職務内容'
    skill: '求めるスキル'
    tags: 'この会社が扱う技術'
    price: '単価'
    location: '最寄り駅'
    position: '職種・ポジション'
    contract: '契約形態'
    contract_location: '契約形態最寄り駅'
# POTEPAN
potepan:
  company_name: 'ポテパン'
  company_id: 2
  url:
    host: 'https://freelance.potepan.com'
    new_projects: 'https://freelance.potepan.com/project'
  title:
    description: '業務内容'
    required_skills: '必須スキル'
    other_skills: '尚可スキル'
    environment: '開発環境'
    location: '勤務地'
    tags: 'キーワード'
# PEBANK
pebank:
  company_name: 'PE-BANK'
  company_id: 3
  url:
    host: 'https://pe-bank.jp'
    new_projects: 'https://pe-bank.jp/project'
  title: